# Question 1

In [94]:
import numpy as np
import pandas as pd

# Question 2

In [95]:
df = pd.read_csv('objects-on-the-moon.csv', delimiter = ',')
df

,Unnamed: 0,Artificial object,Country,Year,Mass (lb),Status,Location,Size
0,0,Luna 2,Soviet Union,1959.0,860,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,NaN
1,1,Luna 2 Third stage of Vostok rocket,Soviet Union,1959.0,20100,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,NaN
2,2,Ranger 4,United States,1962.0,730,Intentionally crashed,15°30′S 130°42′W﻿ / ﻿15.5°S 130.7°W,NaN
3,3,Ranger 6,United States,1964.0,840,Intentionally crashed,9°21′29″N 21°28′48″E﻿ / ﻿9.358°N 21.480°E,NaN
4,4,Ranger 7,United States,1964.0,805,Intentionally crashed,10°38′S 20°36′W﻿ / ﻿10.63°S 20.60°W,NaN
...,...,...,...,...,...,...,...,...
84,84,Hakuto-R Mission 1,Japan,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,NaN
85,85,Emirates Lunar Mission,United Arab Emirates,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,NaN
86,86,Luna 25,Russia,2023.0,3860,Crashed,NaN,NaN
87,87,Chandrayaan-3 Vikram lander Pragyan rover,India,2023.0,3863,Operational,69°22′01″S 32°20′53″E﻿ / ﻿69.367°S 32.348°E,NaN
88,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN

La taille et les quelques lignes sont affichées

In [96]:
df.shape

(89, 8)

On peut également afficher sa taille comme ceci.

# Question 3

In [97]:
df = df.drop(df.columns[0], axis = 1)
df

,Artificial object,Country,Year,Mass (lb),Status,Location,Size
0,Luna 2,Soviet Union,1959.0,860,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,NaN
1,Luna 2 Third stage of Vostok rocket,Soviet Union,1959.0,20100,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,NaN
2,Ranger 4,United States,1962.0,730,Intentionally crashed,15°30′S 130°42′W﻿ / ﻿15.5°S 130.7°W,NaN
3,Ranger 6,United States,1964.0,840,Intentionally crashed,9°21′29″N 21°28′48″E﻿ / ﻿9.358°N 21.480°E,NaN
4,Ranger 7,United States,1964.0,805,Intentionally crashed,10°38′S 20°36′W﻿ / ﻿10.63°S 20.60°W,NaN
...,...,...,...,...,...,...,...
84,Hakuto-R Mission 1,Japan,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,NaN
85,Emirates Lunar Mission,United Arab Emirates,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,NaN
86,Luna 25,Russia,2023.0,3860,Crashed,NaN,NaN
87,Chandrayaan-3 Vikram lander Pragyan rover,India,2023.0,3863,Operational,69°22′01″S 32°20′53″E﻿ / ﻿69.367°S 32.348°E,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
df.shape

(89, 7)

# Question 4

In [99]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Artificial object  88 non-null     str
 1   Country            88 non-null     str
 2   Year               88 non-null     float64
 3   Mass (lb)          88 non-null     str
 4   Status             88 non-null     str
 5   Location           87 non-null     str
 6   Size               0 non-null      float64
dtypes: float64(2), str(5)
memory usage: 12.9 KB

La colonne size est entièrement vide.

# Question 5

In [100]:
df.dropna(how='all', axis=1, inplace = True)
df

,Artificial object,Country,Year,Mass (lb),Status,Location
0,Luna 2,Soviet Union,1959.0,860,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E
1,Luna 2 Third stage of Vostok rocket,Soviet Union,1959.0,20100,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E
2,Ranger 4,United States,1962.0,730,Intentionally crashed,15°30′S 130°42′W﻿ / ﻿15.5°S 130.7°W
3,Ranger 6,United States,1964.0,840,Intentionally crashed,9°21′29″N 21°28′48″E﻿ / ﻿9.358°N 21.480°E
4,Ranger 7,United States,1964.0,805,Intentionally crashed,10°38′S 20°36′W﻿ / ﻿10.63°S 20.60°W
...,...,...,...,...,...,...
84,Hakuto-R Mission 1,Japan,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E
85,Emirates Lunar Mission,United Arab Emirates,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E
86,Luna 25,Russia,2023.0,3860,Crashed,NaN
87,Chandrayaan-3 Vikram lander Pragyan rover,India,2023.0,3863,Operational,69°22′01″S 32°20′53″E﻿ / ﻿69.367°S 32.348°E
88,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
print('Size' in df.columns)

False

# Question 6

In [102]:
df.loc[88]

Artificial object    NaN
Country              NaN
Year                 NaN
Mass (lb)            NaN
Status               NaN
Location             NaN
Name: 88, dtype: object

La ligne est vide !

In [103]:
df.dropna(how='all', inplace=True)
df

,Artificial object,Country,Year,Mass (lb),Status,Location
0,Luna 2,Soviet Union,1959.0,860,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E
1,Luna 2 Third stage of Vostok rocket,Soviet Union,1959.0,20100,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E
2,Ranger 4,United States,1962.0,730,Intentionally crashed,15°30′S 130°42′W﻿ / ﻿15.5°S 130.7°W
3,Ranger 6,United States,1964.0,840,Intentionally crashed,9°21′29″N 21°28′48″E﻿ / ﻿9.358°N 21.480°E
4,Ranger 7,United States,1964.0,805,Intentionally crashed,10°38′S 20°36′W﻿ / ﻿10.63°S 20.60°W
...,...,...,...,...,...,...
83,Manfred Memorial Moon Mission,Luxembourg,2022.0,31,Crashed,5°13′34″N 125°30′50″W﻿ / ﻿5.226°N 125.514°W
84,Hakuto-R Mission 1,Japan,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E
85,Emirates Lunar Mission,United Arab Emirates,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E
86,Luna 25,Russia,2023.0,3860,Crashed,NaN
87,Chandrayaan-3 Vikram lander Pragyan rover,India,2023.0,3863,Operational,69°22′01″S 32°20′53″E﻿ / ﻿69.367°S 32.348°E

Il n'y a plus que 88 lignes.

# Question 7

In [104]:
print(df.dtypes)

Artificial object        str
Country                  str
Year                 float64
Mass (lb)                str
Status                   str
Location                 str
dtype: object

Les masses devraient être des float et non des chaines de caractères.

# Question 8

In [105]:
df['Mass (lb)'].unique()

<ArrowStringArray>
[   '860',  '20100',    '730',    '840',    '805',   '3250',   '3316',
    '220',    '809',   '3500',   '3620',   '3680',    '600',    '249',
    '851',    '644',    '849',    '619',    '624',    '229',    '622',
    '640',   '4874',   '4484',   '5992',   '4815',   '4771',   '3040',
  '12300',  '29661',   '4140',  '30900',   '4727',   '4705',  '30944',
   '6193',    '460',   '4700',     '79', '<12626',  '30869',   '6096',
   '4713',  '30780',   '6169',   '4740',  '10690',    '723',   '8800',
 '<12787',     '26',    '315',    '278',    '677',     '77',    '117',
   '4400',   '4374',   '1500',   '5000',    '293',   '2600',    '547',
    '330',    '104',   '3243', '<18077',   '>400',   '6100',     '31',
    '750',   '3860',   '3863']
Length: 73, dtype: str

Ce sont des str car il y a des < et des >.

# Question 9

In [106]:
df['Mass (lb) orig'] = df['Mass (lb)']
df

,Artificial object,Country,Year,Mass (lb),Status,Location,Mass (lb) orig
0,Luna 2,Soviet Union,1959.0,860,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,860
1,Luna 2 Third stage of Vostok rocket,Soviet Union,1959.0,20100,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,20100
2,Ranger 4,United States,1962.0,730,Intentionally crashed,15°30′S 130°42′W﻿ / ﻿15.5°S 130.7°W,730
3,Ranger 6,United States,1964.0,840,Intentionally crashed,9°21′29″N 21°28′48″E﻿ / ﻿9.358°N 21.480°E,840
4,Ranger 7,United States,1964.0,805,Intentionally crashed,10°38′S 20°36′W﻿ / ﻿10.63°S 20.60°W,805
...,...,...,...,...,...,...,...
83,Manfred Memorial Moon Mission,Luxembourg,2022.0,31,Crashed,5°13′34″N 125°30′50″W﻿ / ﻿5.226°N 125.514°W,31
84,Hakuto-R Mission 1,Japan,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,750
85,Emirates Lunar Mission,United Arab Emirates,2023.0,750,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,750
86,Luna 25,Russia,2023.0,3860,Crashed,NaN,3860
87,Chandrayaan-3 Vikram lander Pragyan rover,India,2023.0,3863,Operational,69°22′01″S 32°20′53″E﻿ / ﻿69.367°S 32.348°E,3863

In [107]:
df ['Mass (lb)'] = pd.to_numeric(df['Mass (lb)'], errors = 'coerce')

In [108]:
print(df ['Mass (lb)'].dtypes, df['Mass (lb)'].isna().sum())

float64 4

Il y a donc 4 valeur manquante.

# Question 10

In [109]:
df['Mass (lb) orig'].dtype

In [113]:
df['Mass (lb) nouveau'] = df['Mass (lb) orig'].str.replace('<', '').str.replace('>', '')

In [120]:
df['Mass (lb) nouveau'].astype(int)
df ['Mass (lb) nouveau'] = pd.to_numeric(df['Mass (lb) nouveau'], errors = 'coerce')

# Question 11

In [121]:
df['Mass (lb) nouveau'].dtype

dtype('int64')

In [122]:
df['Mass (kg)'] = (df['Mass (lb) nouveau'] / 2.205).astype(int)

In [123]:
df

,Artificial object,Country,Year,Mass (lb),Status,Location,Mass (lb) orig,Mass (lb) nouveau,Mass (kg)
0,Luna 2,Soviet Union,1959.0,860.0,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,860,860,390
1,Luna 2 Third stage of Vostok rocket,Soviet Union,1959.0,20100.0,Intentionally crashed,29°06′N 0°00′E﻿ / ﻿29.1°N 0°E,20100,20100,9115
2,Ranger 4,United States,1962.0,730.0,Intentionally crashed,15°30′S 130°42′W﻿ / ﻿15.5°S 130.7°W,730,730,331
3,Ranger 6,United States,1964.0,840.0,Intentionally crashed,9°21′29″N 21°28′48″E﻿ / ﻿9.358°N 21.480°E,840,840,380
4,Ranger 7,United States,1964.0,805.0,Intentionally crashed,10°38′S 20°36′W﻿ / ﻿10.63°S 20.60°W,805,805,365
...,...,...,...,...,...,...,...,...,...
83,Manfred Memorial Moon Mission,Luxembourg,2022.0,31.0,Crashed,5°13′34″N 125°30′50″W﻿ / ﻿5.226°N 125.514°W,31,31,14
84,Hakuto-R Mission 1,Japan,2023.0,750.0,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,750,750,340
85,Emirates Lunar Mission,United Arab Emirates,2023.0,750.0,Crashed,47°34′52″N 44°05′38″E﻿ / ﻿47.581°N 44.094°E,750,750,340
86,Luna 25,Russia,2023.0,3860.0,Crashed,NaN,3860,3860,1750
87,Chandrayaan-3 Vikram lander Pragyan rover,India,2023.0,3863.0,Operational,69°22′01″S 32°20′53″E﻿ / ﻿69.367°S 32.348°E,3863,3863,1751

# Question 12

In [124]:
df['Country'].unique()

<ArrowStringArray>
[         'Soviet Union',         'United States',                 'Japan',
 'European Space Agency',                 'India',                 'China',
                'Israel',            'Luxembourg',  'United Arab Emirates',
                'Russia']
Length: 10, dtype: str

In [126]:
df_copy = df[['Country','Mass (kg)']]
df_copy = df_copy.groupby('Country').sum()
df_copy

                       Mass (kg)
Country
China                      15545
European Space Agency        307
India                       3255
Israel                       149
Japan                       2529
Luxembourg                    14
Russia                      1750
Soviet Union               58723
United Arab Emirates         340
United States             109604

In [128]:
tot = df['Mass (kg)'].sum()
df_copy['Mass (%)'] = (df_copy['Mass (kg)']/tot)*100
df_copy

                       Mass (kg)   Mass (%)
Country
China                      15545   8.087256
European Space Agency        307   0.159716
India                       3255   1.693407
Israel                       149   0.077517
Japan                       2529   1.315707
Luxembourg                    14   0.007283
Russia                      1750   0.910434
Soviet Union               58723  30.550526
United Arab Emirates         340   0.176884
United States             109604  57.021268

# Question 13

In [129]:
print(tot)

192216